### ISSUE TITLE
Quick Start Studio 14 Translation

### ISSUE THREAD

**Issue by lokalova** [cuba-platform/website-content#13] opened 2020-07-09 11:35 UTC
[QuickStart_Studio14.docx](https://github.com/cuba-platform/website-content/files/4896431/QuickStart_Studio14.docx)

The text has a few updates, highlighted. Also available in Google Docs: https://docs.google.com/document/d/12L2o95YD4rpFDCMwk1tNxfDm8lJ4cYpqff1AdSlwl54/edit?usp=sharing

**Comment by jingjingan** [comment] 2020-07-10 03:51
I made change directly in the Google Docs. Let me know if I need to apply the change somewhere else.

**Comment by pfurini** [comment] 2020-07-13 10:49
Hi, the highlighted changes does not reflect the actual changes, at least for the Italian version. There's a lot more to change.

See the english captions in the original google sheet, that's what has been translated in Italian so far, and the captions are quite different now (for example the introduction is changed mostly entirely).

REF: https://docs.google.com/spreadsheets/d/1Ln_QNkQQMFi4zKsa_Z4U8xJho5Zxfj0brSpo9sVF61Y/edit#gid=0

**Comment by pfurini** [comment] 2020-07-13 10:52
PS: I propose to add the quick start immediately to this project too (as MD format), so to start keeping track of changes from now on, and avoid using Gdocs

**Comment by zhenyazb** [comment] 2020-07-14 11:33
@pfurini @BryanYin @jingjingan 
Hi, we've added [subtitles](https://github.com/cuba-platform/website-content/blob/master/Learning%20Materials/Quick%20Start/Subtitles/Subtitles%20EN.md) in MD format to this project. All the changes from the previous version of the quick start you can find in the [commit](https://github.com/cuba-platform/website-content/commit/c7fb52633240cd010829cbd270681948950477e2).

**Comment by lokalova** [comment] 2020-08-28 08:44
> PS: I propose to add the quick start immediately to this project too (as MD format), so to start keeping track of changes from now on, and avoid using Gdocs

Hi @pfurini ,
We've just found out that we forgot to ask you to update the text QS (https://github.com/cuba-platform/website-content/blob/master/Learning%20Materials/Quick%20Start/Text%20Guides/Guide%20EN.md), too. Could you do that?

**Comment by pfurini** [comment] 2020-09-24 15:21
Hi, what about this file: https://github.com/cuba-platform/website-content/blob/master/Learn/Quick%20Start/QS%20IT.md

It is empty now, but it seems a duplicate of the "Text Guides" (the one I've just finished translating). Can we get rid of this folder?

**Comment by lokalova** [comment] 2020-09-25 06:12
@pfurini yeah, I see the folder created by Zhenya Zbitskaya (https://github.com/cuba-platform/website-content/tree/master/Learning%20Materials), I'll check which folder has the latest versions of learning materials ans delete one, thanks

**Closed as completed** 2020-09-25 11:50 UTC
